name: Actions 😎

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  githubToken: ${{ secrets.GIT_TOKEN }}
  
jobs:
  test:
    name: Test my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
    steps:
      - name: Create artifact dir
        run: |
            mkdir -p artifacts
      # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: ${{ matrix.projectPath }}
      # Result
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}
      # Build
      # - name: Build project
        # uses: game-ci/unity-builder@v2
        # env:
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        # with:
          # targetPlatform: WebGL

      # Output
      # - uses: actions/upload-artifact@v2
        # with:
          # name: Build
          # path: build
