name: Actions 😎

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  githubToken: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  test:
    name: Test my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          testMode: EditMode

      # Build
      # - name: Build project
        # uses: game-ci/unity-builder@v2
        # env:
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        # with:
          # targetPlatform: WebGL

      # Output
      # - uses: actions/upload-artifact@v2
        # with:
          # name: Build
          # path: build
